apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: devops
spec:
  type: NodePort
  selector:
    app: frontend-app
  ports:
    - port: 80          # port du service dans le cluster
      targetPort: 80    # port du container Nginx
      nodePort: 30081   # port exposé sur Minikube (doit être entre 30000-32767)
