apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: devops
spec:
  replicas: 1                 # Un seul pod MySQL
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root123
            - name: MYSQL_DATABASE
              value: springdb
            - name: MYSQL_USER
              value: spring
            - name: MYSQL_PASSWORD
              value: spring123
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql   # Dossier data MySQL dans le conteneur
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc          # Lien vers le PVC
