apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
  namespace: devops
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/springdb
---
apiVersion: v1
kind: Secret
metadata:
  name: spring-secret
  namespace: devops
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: c3ByaW5n    # "spring" en base64
  SPRING_DATASOURCE_PASSWORD: c3ByaW5nMTIz  # "spring123" en base64
